services:
  # --- Auth Service ---
  ngelmak-auth:
    build: .
    container_name: ngelmak-auth
    environment:
      BOOTSTRAP_DB_USERNAME: ${BOOTSTRAP_DB_USERNAME}
      BOOTSTRAP_DB_PASSWORD: ${BOOTSTRAP_DB_PASSWORD}
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      LIQUIBASE_RUN: ${LIQUIBASE_RUN}
    networks:
      - ngelmak-net

networks:
  ngelmak-net:
    external: true