services:
  # --- Auth Service ---
  auth:
    build: .
    container_name: auth
    environment:
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
    depends_on:
      - postgres
      - redis
    networks:
      - ngelmak-net

networks:
  ngelmak-net:
    external: true