spring:
  application:
    name: "Ngelmak Project - Auth"
    support:
      email: support@ngelmak.org
      phone: +33 X XX XX XX XX
      address: 
      facebook-url: "#"
      twitter-url: "#"
      instagram-url: "#"
  config:
    import: vault:// # Enable Vault as a Config Data source
  cloud:
    vault:
      uri: http://vault:8200
      authentication: approle
      fail-fast: true # Enable fail-fast to force confirmation. Spring Boot to crash immediately when Vault/OpenBao is not reachable
      app-role:
        role-id: ${VAULT_ROLE_ID}
        secret-id: ${VAULT_SECRET_ID}
      database:
        enabled: true
        backend: database
        role: ngelmak-springboot-role # The Vault role that has permissions to access the database credentials
      kv:
        enabled: true
        backend: secret
        application-name: jjwt,email/noreply
        default-context: ""  # or omit this entirely
  datasource:
    hikari:
      initialization-fail-timeout: 0
    url: jdbc:postgresql://postgres:5432/ngelmakauthdb
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none # Use application-bootstrap.yml for updating the database schema
  jackson:
    serialization:
      fail-on-empty-beans: false
  servlet:
    multipart:
      enabled: true
      max-file-size: 30MB
      max-request-size: 30MB
      resolve-lazily: false
  resources:
    cache-period: 86400
  
debug: false
logging:
  level:
    root: INFO

server:
  port: 37273

# Spring Mail Configuration
spring.mail.host: mail.ngelmak.org
spring.mail.port: 587
spring.mail.username: no-reply@ngelmak.org
spring.mail.password: ${noreply-password}
spring.mail.properties.mail.smtp.auth: true
spring.mail.properties.mail.smtp.starttls.enable: true
spring.mail.properties.mail.smtp.starttls.required: true
spring.mail.properties.mail.smtp.connectiontimeout: 5000
spring.mail.properties.mail.smtp.timeout: 5000
spring.mail.properties.mail.smtp.writetimeout: 5000
spring.mail.properties.mail.smtp.ssl.protocols: TLSv1.2
spring.mail.properties.mail.smtp.ssl.trust: mail.ngelmak.org